### PR TITLE
Remove 8kB read-ahead from couch_file

### PR DESCRIPTION
**Pull request by nickva**
In production it showed an increased input Erlang IO and increased binary
memory usage.

See attached file in Jira ticket:

COUCHDB-3284

### CODE REVIEW

**Comment by kxepal** [comment]
@nickva 
You're going to revert [this optimization](https://github.com/apache/couchdb-couch/commit/c7b30071ac1a4166d44fc10f760a1a8ae2a8ae5c). Won't this impact on something else?

**Comment by kxepal** [comment]
Hm...just checked your graphs in JIRA. They looks very nice.

**Comment by nickva** [comment]
Out of curiosity create a branch which allows configuring file:open's read_ahead parameter:

https://github.com/cloudant/couchdb-couch/commit/3e35ae40f71fa84a3453b178caf774147300e87d

**Comment by davisp** [comment]
Awesome find. I've definitely been perplexed by the I/O changes since starting to deploy Couch 2.0 code. This definitely seems to explain both the io differences and the increase in memory usage. 

The original commit even calls this a micro optimization so I'm inclined to completely remove it rather than make it optional. @kxepal, are you wanting to see a config option or are the graphs on the ticket convincing enough to just drop it?

Huge +1 from me.

**Comment by kxepal** [comment]
@davisp 
No, I'm waiting to have this merged (: 
I wrote first post without knowledge about graphs, which are impressive - that's why reverting optimization for another optimization I found a bit strange.

+1 - that's what I forgot to add.

**Comment by rnewson** [comment]
+1

**Comment by rnewson** [comment]
for clarity, we strongly believe the readahead to be a significant performance _regression_. It's not an improvement in any scenario we can see.

**Pull request merged**
