### PR TITLE
2898 improve global changes tests

### PR DESCRIPTION
**Pull request by jaydoane**

### CODE REVIEW

**Comment by kxepal** [comment]
Don't you actually hide an issue with e7b3ba4 commit? Slash character is used by global_changes for specific logic owner.

**Comment by jaydoane** [comment]
Yes, it's possible that there's a bug downstream that's triggered by the "/" in the db name. It works correctly for one of the downstream builds, but fails in the other. @kxepal, if you prefer, I can omit that commit.

**Comment by kxepal** [comment]
I think you should omit that commit in order to not forget about the bug and fix it in downstream (: There is no better reminder as build failure.

**Comment by jaydoane** [comment]
@kxepal, I've removed the offending commit.

**Comment by kxepal** [comment]
+1

**Pull request merged**
