### PR TITLE
add couch_util:with_proc/{3,4}

### PR DESCRIPTION
**Pull request by chewbranca**
BugzId: 2657

### CODE REVIEW

**Comment by kxepal** [comment]
Commit message references to the nonexisted with_proc/3
A little bit notice why with_proc exists and what it does would be awesome (:

**Comment by chewbranca** [comment]
hah good call @kxepal. I'll rename the commit and I'm just going to cherry-pick it in so I'll leave this PR as is rather than recreating one.

**Comment by kxepal** [comment]
+1

**Comment by chewbranca** [comment]
Merged manually.

**Pull request closed without merging**
