### PR TITLE
Avoid arithmetic in `to_hex` function

### PR DESCRIPTION
**Pull request by iilyak**

### CODE REVIEW

**Comment by rnewson** [comment]
how much of a boost is this?

**Comment by iilyak** [comment]
new         | old   
-------------|-------------
1096247 | 1489097 

Note: The number is a 99.9% for 10000 runs with 1000 bytes of data

**Comment by kxepal** [comment]
+1

**Comment by kxepal** [comment]
If you're interested, we played in to_hex benchmark two years ago. Summary could be found here: https://gist.github.com/maxlapshin/6809909
Matching with function clause is really the fastest method to do the things in Erlang.

**Comment by robertkowalski** [comment]
wow thats quite cool! :)

**Comment by rnewson** [comment]
+1

**Comment by kocolosk** [comment]
+1 as well. Good use of the module constant pool and pattern matching to avoid the arithmetic here.

**Comment by iilyak** [comment]
Thank you @kocolosk for the idea to use body recursion.

**Pull request merged**
