### PR TITLE
Fix crypto deprecations

### PR DESCRIPTION
**Pull request by rnewson**
COUCHDB-2825

### CODE REVIEW

**Comment by kxepal** [comment]
+1 here and for others.

P.S. You miss couch-epi, I handled it: https://github.com/apache/couchdb-couch-epi/pull/11

**Comment by rnewson** [comment]
I deliberately skipped it as it calls erlang:md5 which is not deprecated and to avoid making it depend on couchdb.

**Comment by kxepal** [comment]
Ah, ok. I'll close it then.

**Comment by kxepal** [comment]
However, it still emits crypto warning. I changed PR to handle it in different way.

**Pull request merged**
