### PR TITLE
Reject database names with path segments over 128 characters

### PR DESCRIPTION
**Pull request by rnewson**
COUCHDB-2821

### CODE REVIEW

**Comment by kxepal** [comment]
+1

**Comment by kxepal** [comment]
Alternative solution:

```
diff --git a/src/couch_db.erl b/src/couch_db.erl
index 6f767d9..877e907 100644
--- a/src/couch_db.erl
+++ b/src/couch_db.erl
@@ -1514,7 +1514,10 @@ validate_dbname(DbName) when is_binary(DbName) ->
 validate_dbname_int(DbName, Normalized) when is_binary(DbName) ->
     case re:run(DbName, ?DBNAME_REGEX, [{capture,none}, dollar_endonly]) of
         match ->
-            ok;
+            case validate_part_lengths(DbName) of
+                ok -> ok;
+                error -> {error, {database_name_too_long, DbName}}
+            end;
         nomatch ->
             case is_systemdb(Normalized) of
                 true -> ok;
@@ -1522,6 +1525,15 @@ validate_dbname_int(DbName, Normalized) when is_binary(DbName) ->
             end
     end.
 
+validate_part_lengths(DbName) when is_binary(DbName)->
+  validate_part_lengths(filename:split(DbName));
+validate_part_lengths([]) ->
+    ok;
+validate_part_lengths([Part | Rest]) when byte_size(Part) =< 128 ->
+    validate_part_lengths(Rest);
+validate_part_lengths([Part | Rest]) when byte_size(Part) > 128 ->
+    error.
+
```

It makes `validate_dbname_int` looks nice:
```
validate_dbname_int(DbName, Normalized) when is_binary(DbName) ->
    case re:run(DbName, ?DBNAME_REGEX, [{capture,none}, dollar_endonly]) of
        match ->
            case validate_part_lengths(DbName) of
                ok -> ok;
                error -> {error, {database_name_too_long, DbName}}
            end;
        nomatch ->
            case is_systemdb(Normalized) of
                true -> ok;
                false -> {error, {illegal_database_name, DbName}}
            end
    end.
```

**Comment by kxepal** [comment]
+1 for new version.

**Comment by kxepal** [comment]
There is a problem with shards:
```
$ http put http://localhost:15984/ebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617ad
HTTP/1.1 201 Created
Cache-Control: must-revalidate
Content-Length: 12
Content-Type: text/plain; charset=utf-8
Date: Tue, 22 Sep 2015 10:14:44 GMT
Location: http://localhost:15984/ebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617ad
Server: CouchDB/cb58087 (Erlang OTP/18)
X-Couch-Request-ID: 6f65159f96
X-CouchDB-Body-Time: 0

{"ok":true}

$ http get http://localhost:15984/ebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617ad
HTTP/1.1 500 Internal Server Error
Cache-Control: must-revalidate
Content-Length: 91
Content-Type: text/plain; charset=utf-8
Date: Tue, 22 Sep 2015 10:16:16 GMT
Server: CouchDB/cb58087 (Erlang OTP/18)
X-Couch-Request-ID: 757fde0712
X-Couch-Stack-Hash: 931695309
X-CouchDB-Body-Time: 0

{"error":"internal_server_error","reason":"No DB shards could be opened.","ref":931695309}
```

Obliviously, there are no shards, because:
```
mem3_shards tried to create shards/e0000000-ffffffff/ebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617ad.1442916620, got {error,{database_name_too_long,<<"shards/e0000000-ffffffff/ebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617bbebd6af834f824cff9f8b4ed4bb6617ad.1442916620">>}}
```

So technically PR is correct, but not for shards. Revoking my +1. Sorry for missing that case.

**Comment by rnewson** [comment]
Replaced by https://github.com/apache/couchdb-fabric/pull/31. I think it makes more sense to ensure the enametoolong error percolates up and prevents the 'dbs' doc being created in the first place. For non-sharded databases, the enametoolong error is already fatal, so nothing needs to happen in couchdb-couch.

**Pull request closed without merging**
