### PR TITLE
Temporarily lock out authentication attempts after repeated failures

### PR DESCRIPTION
**Pull request by rnewson**
COUCHDB-2778

### CODE REVIEW

**Comment by kxepal** [comment]
```$ git apply 88.patch
88.patch:209: new blank line at EOF.
+
warning: 1 line adds whitespace errors.
```

**Comment by kxepal** [comment]
Behavior is strange: when lock happens CouchDB doesn't sends any response back holding the connection. So I believe, this could be used to cause resources leak on server.

**Comment by rnewson** [comment]
for a lockout to be effective it has to slow the attacker, the only way to do that is to make requests take longer. That does tie up the socket, sadly. Any thoughts?

**Comment by kxepal** [comment]
@rnewson I think, much better to just log it and configure fail2ban or similar system which will generate firewall rules about. TARPIT for iptables can cause a lot of troubles for attacker and it's much more effective that we can implement. So far, there is no need to implement poor man firewall with which we can shoot ourselfs.

**Comment by kxepal** [comment]
Also, it seems locking doesn't happens if I provide non existed username. So with current behaviour I can figure which users are registered during bruteforce.

**Comment by rnewson** [comment]
two good points, will ponder.

**Comment by rnewson** [comment]
I'll rethink, thanks for the feedback.

**Pull request closed without merging**
