### PR TITLE
1145  local docs handler

### PR DESCRIPTION
**Pull request by iilyak**

### CODE REVIEW

**Comment by kxepal** [comment]
/cc @rnewson @chewbranca @davisp 

While I found the solution a bit complicated, I see it works and solves the main problem. So I'm happy to merge this and if it will be actual simplify (if it is ever possible) later. But would be also good if you take a look on the changes.

**Comment by kxepal** [comment]
I'd plan to merge this branch, but something went wrong and `GET /db/_local_docs` and `GET /db/_design_docs` always returns the same content as `GET /db/_all_docs`. Also, if I remove handlers definition from ini file, these endpoints continue to be available. @iilyak could you check this?

**Comment by kxepal** [comment]
Nvm, PR for couchdb-couch-mrview wasn't mentioned in COUCHDB-1145, I miss it. Please check if all the correct:
https://github.com/apache/couchdb-documentation/pull/10
https://github.com/apache/couchdb-fabric/pull/8
https://github.com/apache/couchdb-chttpd/pull/16
https://github.com/apache/couchdb/pull/291
https://github.com/apache/couchdb-couch-mrview/pull/13
And this one. 6 in total.

**Comment by iilyak** [comment]
Looks correct

**Comment by kxepal** [comment]
@iilyak all merged. Thank you!

**Comment by rnewson** [comment]
added without tests. :(

**Comment by kxepal** [comment]
@rnewson nothing is forgotten. will be added.

**Pull request merged**
