### PR TITLE
Fix error handling in couch_util:with_proc

### PR DESCRIPTION
**Pull request by chewbranca**

### CODE REVIEW

**Comment by kxepal** [comment]
Oh..I overlooked this as well. Btw, aren't Errors are already happens in {error, foo} format? Or there is no reason to be ensured in that?

**Comment by chewbranca** [comment]
@kxepal yeah slipped by me as well. The errors don't have an error flag when they're the return value of a process exiting, as you can see below.


```
(node1@127.0.0.1)32> spawn_monitor(fun() -> erlang:error({foo,bar}) end), flush().
Shell got {'DOWN',#Ref<4555.0.10.2310>,process,<4555.13982.1>,
                  {{foo,bar},[{erlang,apply,2,[]}]}}
ok
```

**Comment by iilyak** [comment]
+1

**Comment by kxepal** [comment]
@chewbranca eh, ok, I had good hope on them (: 

+1

**Comment by chewbranca** [comment]
Manually merged.

**Pull request closed without merging**
