### PR TITLE
Throw bad request for empty POST request body when filtering by doc_ids

### PR DESCRIPTION
**Pull request by jaydoane**
JIRA: COUCHDB-2743
BugzID: 48864

### CODE REVIEW

**Comment by jaydoane** [comment]
Please see https://github.com/apache/couchdb-couch/pull/68 for discussion.

**Comment by rnewson** [comment]
:/ please fix #67 instead.

**Comment by jaydoane** [comment]
Going to try closing this PR in the hopes that doing so may allow me to re-open #67.

**Comment by jaydoane** [comment]
No, the UI is not allowing me to re-open #67.

**Comment by rnewson** [comment]
+1. I'll merge this.

**Comment by kxepal** [comment]
@jaydoane Did you test your patch with local interface? I think, it broke something useful:

```
$ curl -v -XPOST http://localhost:59860/db/_changes?filter=_doc_ids -d '{"doc_ids": ["test"]}' -H 'Content-Type:application/json'
*   Trying ::1...
* connect to ::1 port 59860 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 59860 (#0)
> POST /db/_changes?filter=_doc_ids HTTP/1.1
> Host: localhost:59860
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 21
> 
* upload completely sent off: 21 out of 21 bytes
< HTTP/1.1 400 Bad Request
< Server: CouchDB/e858e7d (Erlang OTP/18)
< Date: Sat, 11 Jul 2015 22:04:24 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 127
< Cache-Control: must-revalidate
< 
{"error":"bad_request","reason":"`_doc_ids` filter requires JSON object body with field \"doc_ids\" containing array of ids."}
* Connection #0 to host localhost left intact
```

**Comment by jaydoane** [comment]
I did test, but not this particular case, unfortunately. I agree that it's broken because of that patch. Going to poke around a bit to see if it can be repaired.

**Comment by rnewson** [comment]
This has been reverted.

**Pull request merged**
