### PR TITLE
48864 bad request on post missing body doc ids filter

### PR DESCRIPTION
**Pull request by jaydoane**

### CODE REVIEW

**Comment by jaydoane** [comment]
Hmm, of course I was only trying to pull my own changes in...

**Comment by rnewson** [comment]
rebase? :)

**Comment by jaydoane** [comment]
Righto.

**Comment by rnewson** [comment]
@jaydoane you can do it here, force-push when you have the 1 commit version you intended.

**Comment by jaydoane** [comment]
I couldn't figure out how to push here, but have opened PR 67 which hopefully has the correct changes.

**Pull request closed without merging**
