### PR TITLE
CSRF is not necessary for read operations

### PR DESCRIPTION
**Pull request by rnewson**
COUCHDB-2762

### CODE REVIEW

**Comment by kxepal** [comment]
+1

I see only problems with _update handler(where GET is disabled on query server side, not httpd => custom query server may create/modify documents on GET) and custom externals which could not respect REST and do modifications on GET, but here we can nothing much to do.

**Comment by rnewson** [comment]
Any preference for a single clause version?

`validate(#httpd{method = Method}) when Method == 'GET'; Method == 'HEAD'; Method == 'OPTIONS' ->`

**Comment by kxepal** [comment]
@rnewson if you fit it in 80 line right margin - ok (: Personally, I found your initial version more readable - less syntax noise around the valuable data, but fine with both solutions.

**Comment by rnewson** [comment]
I'll go with the original then. thanks!

**Pull request merged**
